# Generated by Django 5.0.3 on 2024-04-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_videodb_video_file_videodb_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodb',
            name='name',
        ),
    ]
