# Generated by Django 5.0.3 on 2024-04-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_videodb_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodb',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
