# Generated by Django 5.0.3 on 2024-04-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_videodb_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videodb',
            old_name='name',
            new_name='Tname',
        ),
    ]
