# Generated by Django 5.0.3 on 2024-04-02 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_rename_name_videodb_tname'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodb',
            name='videofile',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
